build_tags:
  script:
    - docker build --build-arg env=production -t docker.blued.cn/blued/<%= project %>:"$CI_BUILD_TAG" .
    - docker push docker.blued.cn/blued/<%= project %>:"$CI_BUILD_TAG"
    - docker rmi docker.blued.cn/blued/<%= project %>:"$CI_BUILD_TAG"
  only:
  - /^pro.*$/
  except:
  - branches

build_master:
  script:
    - docker build --build-arg env=development -t docker-test.blued.cn/blued/<%= project %>:"$CI_BUILD_TAG" .
    - docker push docker-test.blued.cn/blued/<%= project %>:"$CI_BUILD_TAG"
    - docker rmi docker-test.blued.cn/blued/<%= project %>:"$CI_BUILD_TAG"
  only:
  - /^dev.*$/
  except:
  - branches
