build_tags:
  script:
    - docker build --build-arg env=production -t docker.blued.cn/blued/<%= project %> .
    - docker push docker.blued.cn/blued/<%= project %>
    - docker rmi docker.blued.cn/blued/<%= project %>
  only:
  - tags

build_master:
  script:
    - docker build --build-arg env=development -t docker.blued.cn/blued/<%= project %> .
    - docker push docker.blued.cn/blued/<%= project %>
    - docker rmi docker.blued.cn/blued/<%= project %>
  only:
  - master
